# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'ğŸ”¶'
[character] # The name of the module we are configuring is 'character'
success_symbol = "ğŸ”¶" # The 'success_symbol' segment is being set to 'ğŸ”¶'
error_symbol = "âŒ"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
