# Starship configuration for colored-lozenges prompt.
#
# STRUCTURE
# This is a two-line prompt:
# - Line 1:
#   - Left-justified items
#     - username (conditionally displayed)
#       - White lozenge
#       - Displays username only if any of the following conditions are met:
#         - the current user is root/admin
#         - the current user isnâ€™t the same as the one that is logged in
#         - the user is currently connected as an SSH session
#         - the variable `show_always` is set to `true`
#       - To test how the username module displays within the prompt, in the `[username]` module below, change `show_always` to `always`
#     - directory
#       - Blue lozenge
#       - if current directory is in a git repository, truncates the path to the root of the repo
#       - TODO: Experiment with value for `truncation_length` to ensure first line of prompt is not too long
#       - CONSIDER: Use `substitutions` to provide short name for literal strings that occur in path.
#         However, these are likely to be user-specific, so would have to figure out how to allow each user to make modifications to
#         to starship.toml without screwing up the propagation of changes to all users.
#     - git summary
#       - Yellow lozenge
#       - Three components
#         - branch (conditionally displayed)
#           - the branch is displayed only if the branch is *not* 'main' or 'master'
#             - this behavior can be reversed (i.e., branch is unconditionally displayed, even if 'main' or 'master') by,
#               in module `[git_branch]` below, commenting out the `ignore_branches` line
#         - commit hash
#         - status
#           - TODO: Revisit the symbols assigned to various conditions in a real-world context.
#             Note: Iâ€™ve currently overridden the assigned symbols with a bunch of emojis that arenâ€™t readily informative.
#   - Right-justified items
#     - Elapsed time for command (conditionally displayed)
#       - Prefaced with an hourglass emoji ('â³'); not a lozenge
#     - Month/day and time
#       - Not a lozenge
#         - Month/day
#           - Prefaced with a calendar-page emoji ('ğŸ“…') ; three-letter month; day of month is *not* padded
#         - Time
#           - Prefaced with a watch emoji ('â±ï¸')
# - Line 2 (all left justified):
#   - SUDO (conditionally displayed)
#     - "SUDO" in an orange lozenge
#     - is displayed only if sudo credentials are current cached (at the time the prompt is rendered)
#     - Note: sudo credentials can expire with the passage of time, but a previously rendered "SUDO" will be retroactively removed.
#   - Prompt â€œcharacterâ€
#     - A yellow right arrow (formed by two characters)
#
# SPECIAL CHARACTERS RELIED UPON
# - Nerd Font characters
#   - Unicode, classname, description, purpose
#     - E0B6 nf-ple-left_half_circle_thick    half-circle for left-end cap on lozenges
#     - E0B4 nf-ple-right_half_circle_thick   half-circle for right-end cap on lozenges
#     - F0C8 nf-fa-square                     square for first character of success_symbol in `[character]` module
#     - E0B0 nf-pl-left_hard_divider          right-pointing solid triangle for second character of success_symbol in `[character]` module



# e0b6 left_half_circle_thick
# e0b4 nf-ple-right_half_circle_thick
# e0b0 nf-pl-left_hard_divider
# f0c8 nf-fa-square
# e709 GitHub badge
# f418 git branch
# f07c nf-fa-folder_open
# [î‚¶](bg:#030B16 fg:blue)\
# [î‚¶](bg:none fg:#FCF392)[$git_branch$git_commit$git_status](bg:none fg:#FCF392)[î‚´ ](bg:none fg:#FCF392)\
# 2025_08_08_2004 [([î‚¶](bg:none fg:#FCF392)[îœ‰ ](bg:#FCF392)$git_branch$git_commit$git_status[î‚´ ](bg:none fg:#FCF392))](bg:none fg:#FCF392)\
# 2025_08_08_2006 [(î‚¶[îœ‰ ](bg:#FCF392)$git_branch$git_commit$git_status[î‚´ ](bg:none fg:#FCF392))](bg:none fg:#FCF392)\
# 2025_08_08_2011 [(î‚¶[îœ‰ ](bg:#FCF392)($git_branch$git_commit$git_status)î‚´ )](fg:#FCF392)\
# 2025_08_09_1104 '[î‚¶](bg:#030B16 fg:username_primary)[ğŸ‘¤ $user ]($style)[î‚´](bg:#030B16 fg:username_primary) '
format = """
$username\
$directory \
[(î‚¶[îœ‰ ](bg:git_primary)($git_branch$git_commit$git_status)î‚´ )](fg:git_primary)\
$fill\
$python\
$docker_context\
$cmd_duration\
$time\
$line_break\
$sudo\
$character\
$status"""

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Specify color palette
palette = "lozenges_darkmode"
# palette = "lozenges_lightmode"

[username]
format = '[î‚¶](fg:username_primary)[ğŸ‘¤ $user ]($style)[î‚´](fg:username_primary) '
style_user = 'bg:username_primary fg:username_contrast'
show_always = true
disabled = false

[directory]
home_symbol = 'ğŸ '
format = '[î‚¶](fg:directory_primary)[ï¼: $path ]($style)[$read_only]($read_only_style)[î‚´](fg:directory_primary)'
style = 'bg:directory_primary fg:directory_contrast'
truncate_to_repo = true
truncation_length = 3
truncation_symbol = 'â€¦/'
disabled = false

[git_branch]
# ignore_branches = ["main", "master"]
symbol = 'ï˜'
format = '[$symbol $branch(:$remote_branch)]($style)'
style = 'bg:git_primary fg:git_contrast'
disabled = false

[git_commit]
format = '[ #$hash $tag]($style)'
style = 'bg:git_primary fg:git_contrast'
tag_disabled = false
only_detached = false
disabled = false

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'
style = 'bg:git_primary fg:git_contrast bold'
format = '([$all_status$ahead_behind]($style))'
disabled = false

[fill]
symbol = ' â€¢  '
disabled = false

[cmd_duration]
format = '\(â³ [$duration]($style)\) '
style = 'bold time_related_font_color'
disabled = false

[time]
format = '[$time]($style) '
time_format = ' ğŸ“… %h %-e â±ï¸ %T'
style = 'time_related_font_color'
disabled = false

[line_break]
disabled = false

[sudo]
symbol = 'SUDO'
# symbol = 'ğŸš¨SUDOâš¡ï¸'
format = '[î‚¶](fg:sudo_primary)[$symbol]($style)[î‚´](fg:sudo_primary) '
style = 'bg:sudo_primary fg:sudo_contrast bold'
disabled = false

[character] 
# success_symbol = "ğŸ”¶" 
success_symbol = '[ïƒˆî‚°](#FFA500)'
error_symbol = "âŒ"
format = '$symbol '
disabled = false

[palettes.lozenges_darkmode]
directory_primary = '#3B76F0'
directory_contrast = '#E4E4E4'
git_primary = '#FCF392'
git_contrast = '#212121'
username_primary = '#E4E4E4'
username_contrast = '#212121'
sudo_primary = '#FF5F1F'
sudo_contrast = '#E4E4E4'
time_related_font_color = '#FFFF00'

[palettes.lozenges_lightmode]
directory_primary = '#3B76F0'
directory_contrast = '#E4E4E4'
git_primary = '#FCF392'
git_contrast = '#212121'
username_primary = '#E4E4E4'
username_contrast = '#212121'
sudo_primary = '#FF5F1F'
sudo_contrast = '#E4E4E4'
time_related_font_color = '#0000FF'
