format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$python\
$docker_context\
$cmd_duration\
$time\
$line_break\
$username\
$sudo\
$character\
$status"""


# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "ğŸ”¶" 
error_symbol = "âŒ"
disabled = false

[cmd_duration]
format = '\(â³ [$duration]($style)\) '
disabled = false

[directory]
home_symbol = "ğŸ "
truncate_to_repo = false
truncation_length = 10
disabled = false

[git_branch]
ignore_branches = ["main", "master"]
disabled = false

[git_commit]
format = '[\(#ï¸âƒ£  $hash$tag\)]($style) '
tag_disabled = false
only_detached = false
disabled = false

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'
disabled = false

[line_break]
disabled = false

[status]
format = '[\(ERROR $status\)]($style) '
disabled = false

[sudo]
symbol = 'ğŸš¨SUDOâš¡ï¸'
format = '[\($symbol\) ]($style)'
disabled = false

[time]
format = '[$time ]($style) '
time_format = 'ğŸ“… %F â±ï¸ %T'
disabled = false

[username]
format = '\(ğŸ‘¤ [$user]($style)\) '
show_always = true
disabled = false
