# e0b6 left_half_circle_thick
# e0b4 nf-ple-right_half_circle_thick
# e0b0 nf-pl-left_hard_divider
# f0c8 nf-fa-square
# e709 GitHub badge
# f418 git branch
# f07c nf-fa-folder_open
# [î‚¶](bg:#030B16 fg:blue)\
# [î‚¶](bg:none fg:#FCF392)[$git_branch$git_commit$git_status](bg:none fg:#FCF392)[î‚´ ](bg:none fg:#FCF392)\
# 2025_08_08_2004 [([î‚¶](bg:none fg:#FCF392)[îœ‰ ](bg:#FCF392)$git_branch$git_commit$git_status[î‚´ ](bg:none fg:#FCF392))](bg:none fg:#FCF392)\
# 2025_08_08_2006 [(î‚¶[îœ‰ ](bg:#FCF392)$git_branch$git_commit$git_status[î‚´ ](bg:none fg:#FCF392))](bg:none fg:#FCF392)\
# 2025_08_08_2011 [(î‚¶[îœ‰ ](bg:#FCF392)($git_branch$git_commit$git_status)î‚´ )](fg:#FCF392)\
# 2025_08_09_1104 '[î‚¶](bg:#030B16 fg:username_primary)[ğŸ‘¤ $user ]($style)[î‚´](bg:#030B16 fg:username_primary) '
format = """
$username\
$directory \
[(î‚¶[îœ‰ ](bg:git_primary)($git_branch$git_commit$git_status)î‚´ )](fg:git_primary)\
$fill\
$python\
$docker_context\
$cmd_duration\
$time\
$line_break\
$sudo\
$character\
$status"""

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Specify color palette
palette = "lozenges"

[username]
format = '[î‚¶](fg:username_primary)[ğŸ‘¤ $user ]($style)[î‚´](fg:username_primary) '
style_user = 'bg:username_primary fg:username_contrast'
show_always = true
disabled = false

[directory]
home_symbol = 'ğŸ '
format = '[î‚¶](fg:directory_primary)[ï¼: $path ]($style)[$read_only]($read_only_style)[î‚´](fg:directory_primary)'
style = 'bg:directory_primary fg:directory_contrast'
truncate_to_repo = false
truncation_length = 10
disabled = false

[git_branch]
# ignore_branches = ["main", "master"]
symbol = 'ï˜'
format = '[$symbol $branch(:$remote_branch)]($style)'
style = 'bg:git_primary fg:git_contrast'
disabled = false

[git_commit]
format = '[ #$hash $tag]($style)'
style = 'bg:git_primary fg:git_contrast'
tag_disabled = false
only_detached = false
disabled = false

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'
style = 'bg:git_primary fg:git_contrast bold'
format = '([$all_status$ahead_behind]($style))'
disabled = false

[fill]
symbol = ' â€¢  '
disabled = false

[cmd_duration]
format = '\(â³ [$duration]($style)\) '
style = 'bold time_related_font_color'
disabled = false

[time]
format = '[$time]($style) '
# time_format = 'ğŸ“… %F â±ï¸ %T'
time_format = ' ğŸ“… %h %-e â±ï¸ %T'
style = 'time_related_font_color'
disabled = false

[line_break]
disabled = false

[sudo]
symbol = 'SUDO'
# symbol = 'ğŸš¨SUDOâš¡ï¸'
format = '[î‚¶](fg:sudo_primary)[$symbol]($style)[î‚´](fg:sudo_primary) '
style = 'bg:sudo_primary fg:sudo_contrast bold'
disabled = false

[character] 
# success_symbol = "ğŸ”¶" 
success_symbol = '[ïƒˆî‚°](#FFA500)'
error_symbol = "âŒ"
format = '$symbol '
disabled = false

[palettes.lozenges]
directory_primary = '#3B76F0'
directory_contrast = '#E4E4E4'
git_primary = '#FCF392'
git_contrast = '#212121'
username_primary = '#E4E4E4'
username_contrast = '#212121'
sudo_primary = '#FF5F1F'
sudo_contrast = '#E4E4E4'
time_related_font_color = '#FFFF00'
