# e0b6 left_half_circle_thick
# e0b4 nf-ple-right_half_circle_thick
# e0b0 left_hard_divider
# e709 GitHub badge
# f418 git branch
# [î‚¶](bg:#030B16 fg:blue)\
format = """
$directory \
[î‚¶](bg:none fg:#FCF392)[$git_branch$git_commit$git_status](bg:none fg:#FCF392)[î‚´ ](bg:none fg:#FCF392)\
$fill\
$python\
$docker_context\
$cmd_duration\
$time\
$line_break\
$username\
$sudo\
$character\
$status"""

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[directory]
home_symbol = 'ğŸ '
format = '[î‚¶](bg:#030B16 fg:#3B76F0)[ ğŸ“: $path ]($style)[$read_only]($read_only_style)[î‚´](bg:#030B16 fg:#3B76F0)'
style = 'bg:#3B76F0 fg:#E4E4E4 bold'
truncate_to_repo = false
truncation_length = 10
disabled = false

[git_branch]
# ignore_branches = ["main", "master"]"ğŸ "
symbol = 'ï˜'
format = '[îœ‰ $symbol $branch(:$remote_branch)]($style)'
style = 'bg:#FCF392 fg:black bold'
disabled = false

[git_commit]
format = '[ #$hash $tag]($style)'
style = 'bg:#FCF392 fg:black bold'
tag_disabled = false
only_detached = false
disabled = false

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'
style = 'bg:#FCF392 fg:black bold'
format = '([\[$all_status$ahead_behind\]]($style))'
disabled = false

[cmd_duration]
format = '\(â³ [$duration]($style)\) '
disabled = false

[time]
format = '[$time ]($style) '
time_format = 'ğŸ“… %F â±ï¸ %T'
disabled = false

[line_break]
disabled = false

[username]
format = '[ğŸ‘¤ $user]($style) '
style_user = 'bg:3 fg:black bold'
show_always = true
disabled = false

[sudo]
symbol = 'ğŸš¨SUDOâš¡ï¸'
format = '[$symbol ]($style)'
style = 'bg:13 fg:black bold'
disabled = false

[character]
success_symbol = "ğŸ”¶" 
error_symbol = "âŒ"
disabled = false
